<?php
    return [
        'title' => 'Privacyverklaring',
        'content' => 'Deze Twitch-privacyverklaring is van toepassing op uw gebruik van www.twitch.tv en andere websites, toepassingen of geleverde diensten,
        die eigendom zijn van of aangeboden worden door Twitch Interactive, Inc. (en zijn dochterondernemingen, "Twitch") die doorverwijzen naar
        deze privacyverklaring (gezamenlijk de "Twitch-diensten"). Twitch respecteert de privacy van gebruikers, abonnees, uitgevers,
        leden en anderen die de Twitch-diensten bezoeken en gebruiken (gezamenlijk of individueel, "u" of "gebruikers") en wil dat u op de
        hoogte bent van hoe we persoonsgegevens van en over u verzamelen, gebruiken en openbaar maken. Deze verklaring beschrijft ons
        privacybeleid. Door naar www.twitch.tv te gaan, een Twitch-account aan te maken of de Twitch-diensten te gebruiken, aanvaardt u
        het beleid dat wordt beschreven in deze Privacyverklaring, voor zover dat toegestaan is door de wet.
       Voor de doeleinden van gegevensbeschermingswetgeving is Twitch Interactive, Inc., gevestigd op 350 Bush Street, 2nd Floor,
        San Francisco, CA 94104, de "verwerkingsverantwoordelijke" van uw informatie die wordt verzameld als onderdeel van de Twitch-diensten.

       <div class="mb-3">U kunt persoonsgegevens delen tijdens uw gebruik van de Twitch-diensten. Een voorbeeld hiervan is wanneer u informatie over uzelf
        verschaft als onderdeel van het aanmaken van uw Twitch-account. Nog een voorbeeld hiervan is wanneer u bepaalde handelingen uitvoert
        op de Twitch-diensten die openbaar zijn of openbaar van aard zijn, zoals wanneer u content uitzendt, deelneemt aan een chatroom,
        profielinformatie post, een kanaal volgt of u abonneert op een streamkanaal. Vanwege de sociale aard van sommige Twitch-diensten,
        kan die informatie verzameld, gebruikt of openbaar gemaakt worden door anderen die onderdeel uitmaken van de sociale interactie.
        Bovendien zijn sommige functies van de Twitch-diensten ontwikkeld om anderen informatie te geven over gebruikersactiviteit,
        zoals het identificeren van een gebruiker die een bepaalde clip gemaakt heeft of de abonnementsstatus van gebruikers voor een
        bepaald kanaal controleren. We raden u aan tijdens uw gebruik van de Twitch-diensten hier goed bij stil te staan.</div>
        <h4 id="personal_information_twitch_collects_about_you">Persoonsgegevens die Twitch over u verzamelt</h4>
 <p>Wij verzamelen informatie over u op de hieronder vermelde manieren tijdens het aanbieden van de Twitch-diensten. Let erop dat we bepaalde soorten informatie nodig hebben om de Twitch-diensten aan u te leveren. Als u dergelijke informatie niet aan ons levert, of ons vraagt deze informatie te verwijderen, dan kan het niet langer mogelijk voor u zijn om toegang tot de Twitch-diensten te verkrijgen of kunt u deze niet meer gebruiken.</p>
 <ul>
   <li>Door de gebruiker verstrekte informatie: u levert mogelijk informatie over uzelf aan ons, zoals uw naam, stem en foto (in content die u uploadt), Twitch-gebruikersnaam, e-mailadres, postadres, telefoonnummer, creditcardnummer en betalingsgegevens wanneer u zich registreert voor Twitch-diensten, bepaalde content of producten van de Twitch-diensten uploadt, koopt, bekijkt of downloadt. meedoet aan wedstrijden of weggeefacties of anderzijds gebruikmaakt van de functies en functionaliteit van de Twitch-diensten.</li>
   <li>Automatisch verzamelde informatie: wanneer u de Twitch-diensten gebruikt of een van onze e-mails opent, verzamelen en bewaren we automatisch bepaalde informatie over uw systeem door cookies en andere technologieën te gebruiken. Cookies zijn kleine tekstbestanden met een reeks alfanumerieke tekens die naar uw browser gestuurd worden. Zie ons <a href="https://www.twitch.tv/p/legal/cookie-policy">Cookiebeleid</a> voor informatie over wat cookies zijn, hoe ze werken, hoe Twitch ze gebruikt en hoe u ze kunt verwijderen. Voorbeelden van dergelijke informatie die we automatisch verzamelen zijn onder andere het IP-adres (waarin IP staat voor internet protocol, "IP-adres"), een unieke gebruikers-ID, apparaat- en browsertypes en -identificatoren, adressen van doorverwijs- en vertrekpagina\'s, software- en systeemtype en informatie over uw gebruik van de Twitch-diensten. Voorbeelden van hoe Twitch automatisch verzamelde informatie gebruikt zijn onder andere: (a) automatisch de Twitch-applicatie op uw systeem bijwerken, (b) uw gegevens onthouden zodat u deze niet opnieuw hoeft in te voeren tijdens uw bezoek of de volgende keer dat u gebruikmaakt van de Twitch-diensten, (c) op maat gemaakte advertenties, content en informatie aanbieden, (d) de effectiviteit van marketingcampagnes meten, (e) samengevoegde statistieken over sitegebruik monitoren en opslaan, zoals bezoekersaantallen en geopende pagina\'s en (f) uw invoer, inzendingen en status bij promoties en andere activiteiten bijhouden.</li>
   <li>Informatie uit andere bronnen: we bemachtigen mogelijk aanvullende informatie van derden en andere bronnen dan de Twitch-diensten. Het is bijvoorbeeld mogelijk dat we aanvullende informatie verkrijgen van adverteerders, games of diensten waarvan u gebruikmaakt, of sociale medianetwerken (zoals Facebook) waartoe u ons toegang hebt verleend. Wanneer u de Twitch-diensten opent via sociale media of wanneer u de Twitch-diensten verbindt met sociale media, geeft u Twitch toestemming om dergelijke aanvullende informatie en content te verzamelen, bewaren en gebruiken in overeenstemming met deze Privacyverklaring. We bemachtigen mogelijk ook informatie van derde partijen (zoals Riot of Steam) met betrekking tot uw gebruik van dergelijke diensten, waaronder over uw gebruik van de content die u uitzendt via de Twitch-diensten. Wij gebruiken deze informatie ter aanvulling op de informatie die we over u verzamelen om relevantere, veiligere ervaringen aan te bieden met de Twitch-diensten en om de Twitch-diensten, analyses en advertenties te verbeteren. Indien wij informatie uit andere bronnen combineren of associëren met informatie die wij verzamelen via de Twitch-diensten, verwerken wij de gecombineerde informatie in overeenstemming met deze Privacyverklaring.</li>
 </ul>
 <h4 id="how_twitch_uses_personal_information">Hoe gebruikt Twitch persoonlijke informatie?</h4>
 <ul>
   <li>Twitch gebruikt dergelijke informatie om alle functies, functionaliteiten en diensten (nieuw of bestaand) van de Twitch-diensten te beheren, onderhouden, verbeteren, aan te bieden, creëren en ontwikkelen, te voorzien in de beveiliging van onze websites, producten, software of applicaties, relaties met Twitch-accounthouders (bijv. partners, gelieerde ondernemingen) te beheren, waaronder het uitvoeren of ontvangen van betalingen, het verbeteren van de ervaring met Twitch voor gebruikers door aanbevelingen voor content en door content af te leveren die gebruikers hopelijk relevant en interessant vinden, waaronder advertentie- en marketingberichten, u commentaar te laten plaatsen bij content en deel te laten nemen aan online games, wedstrijden of beloningsprogramma\'s, fraude en misbruik te voorkomen en om de gebruikstrends van onze gebruikers te begrijpen.</li>
   <li>We gebruiken uw e-mailadres en/of telefoonnummer om met u te communiceren, waaronder om u te informeren over belangrijke updates van de Twitch-diensten, voor klantenservicedoeleinden of om contact met u op te nemen inzake content die u geplaatst hebt op of hebt gedownload van de Twitch-diensten. Als u geen telefonische meldingen meer wilt ontvangen, stuur dan het woord STOP als antwoord op een van onze berichten. Houd er rekening mee dat we u nog steeds aanvullende informatieve of transactionele meldingen kunnen sturen.</li>
   <li>Twitch stuurt soms promotiemateriaal of -notificaties inzake de Twitch-diensten. Indien u geen promotiemateriaal meer wilt ontvangen, kunt u naar uw accountinstellingen gaan nadat u bent ingelogd bij de Twitch-diensten of de instructies voor afmelden volgen onderaan onze e-mails. Als u een mobiele app hebt geïnstalleerd en u geen pushnotificaties meer wilt ontvangen, kunt u de instellingen wijzigen op uw mobiele apparaat of via de app.</li>
   <li>In bepaalde gevallen zijn wij wettelijk verplicht om uw persoonsgegevens te verzamelen en te verwerken (zoals onze verplichting om gegevens te delen met belastingautoriteiten).</li>
   <li>We vragen mogelijk ook om uw toestemming om uw persoonsgegevens te verwerken voor een specifiek doeleinde dat we naar u communiceren. Indien u instemt met de verwerking van uw persoonsgegevens voor een specifiek doeleinde, kunt u uw toestemming te allen tijde intrekken waarna wij de verwerking van uw gegevens voor dat doeleinde stopzetten.</li>
   <li>Twitch baseert zich op rechtsgronden voor de verwerking van uw persoonsgegevens voor zover toegestaan onder toepasselijke wetgeving, waaronder, maar niet beperkt tot: het nakomen van contractuele verplichtingen, het nemen van maatregelen ter voorbereiding op het aangaan van een overeenkomst, het naleven van wettelijke verplichtingen, uw toestemming en de legitieme doeleinden van Twitch.</li>
 </ul>
 <h4 id="when_twitch_discloses_personal_information">Indien Twitch persoonsgegevens openbaar maakt</h4>
 <p>Wij delen dergelijke informatie zoals hieronder omschreven:</p>
 <ul>
   <li>We maken dergelijke informatie openbaar aan dienstverleners die namens ons werken, bijvoorbeeld om: websitehosting, onderhoud en beveiligingsdiensten te leveren, bestellingen uit te voeren, data-analyse uit te voeren en rapporten op te stellen, bepaalde functionaliteit aan te bieden of om Twitch te helpen bij het verbeteren van de Twitch-diensten en het ontwikkelen van nieuwe diensten en functies. Wij eisen dat deze partijen dergelijke informatie in overeenstemming met deze Privacyverklaring verwerken, wij autoriseren hen slechts om de informatie voor de doeleinden te gebruiken waarvoor ze het ontvangen hebben, en wij eisen van hen dat zij redelijke geheimhoudingsmaatregelen nemen.</li>
   <li>Twitch maakt informatie mogelijk beschikbaar aan gelieerde ondernemingen (entiteiten die eigendom zijn van, eigenaar zijn van of onder gezamenlijk bestuur zijn van Twitch), zoals Amazon.com, Inc. en haar dochterondernemingen die óf onderhevig zijn aan deze Privacyverklaring óf die een beleid hebben opgesteld dat minstens net zo beschermend is als deze Privacyverklaring.</li>
   <li>Twitch maakt gebruikersinformatie mogelijk openbaar indien wij te goeder trouw van mening zijn dat dergelijke openbaarmaking noodzakelijk is om Amerikaanse staats- en federale wetgeving of andere toepasselijke wetgeving over de hele wereld na te leven (bijvoorbeeld van het land waarin u woonachtig bent), of om te reageren op een gerechtelijk bevel, juridisch of ander overheidsverzoek, dagvaarding of bevelschrift, op de wettelijk vereiste manier.</li>
   <li>Twitch behoudt zich ook het recht voor om informatie openbaar te maken die naar onze mening en te goeder trouw gepast of noodzakelijk is om Twitch te beschermen tegen mogelijke aansprakelijkheid of frauduleus of onrechtmatig gebruik of misbruik, om claims of beschuldigingen van derden te onderzoeken of onszelf daartegen te beschermen, om de beveiliging of integriteit van de Twitch-diensten te beschermen of om de rechten, eigendommen of veiligheid van Twitch, onze gebruikers of anderen te beschermen.</li>
 </ul>
 <p>Met uitzondering van het genoemde in deze Privacyverklaring, ontvangt u een bericht wanneer persoonsgegevens over u mogelijk gedeeld worden met derde partijen en krijgt u de kans om ervoor te kiezen de informatie niet te delen.</p>
 <h4 id="data_subject_rights_and_your_choices">Rechten van betrokkenen en Uw keuzes</h4>
 <p>Op de pagina <a href="/p/nl-nl/legal/privacy-choices/"> Privacy-opties </a> van Twitch staan uw privacy-opties met betrekking tot de Twitch-diensten beschreven, inclusief informatie over hoe u informatie die Twitch mogelijk over u bezit kunt bekijken, bijwerken of verwijderen. U kunt weigeren bepaalde informatie met Twitch te delen, in welk geval Twitch u mogelijk niet alle functies en functionaliteit van de Twitch-diensten kan aanbieden. Als u een account voor de Twitch-diensten hebt aangemaakt, dan kunt u mogelijk, afhankelijk van de dienst, uw profielinformatie en voorkeuren wijzigen of uw account uitschakelen door in te loggen en naar instellingen te gaan, bijvoorbeeld <a href="https://www.twitch.tv/">www.twitch.tv</a>. </p>
 <p>Voor andere verzoeken om Twitch\'s gebruik van informatie die u rechtstreeks aan Twitch geleverd hebt te controleren, bij te werken, te verwijderen of anderzijds te beperken, kunt u contact opnemen met privacy@twitch.tv. Voeg uw e-mailadres, naam, adres en telefoonnummer aan uw verzoek toe en geef alle relevante achtergrondinformatie. Om uw privacy en veiligheid te garanderen, nemen we mogelijk stappen om uw identiteit te verifiëren voordat we u toegang verlenen tot of correcties aanbrengen aan uw informatie. U bent te allen tijde verantwoordelijk voor de geheimhouding van uw unieke wachtwoord en accountinformatie.</p>
 <p>Inwoners van de Europese Economische Ruimte ("EER") kunnen gebruikmaken van bepaalde rechten van betrokkenen onder toepasselijke gegevensbeschermingswetgeving.  Wij willigen verzoeken inzake de uitoefening van deze rechten in, in overeenstemming met toepasselijke wetgeving. Houd er echter rekening mee dat we in bepaalde gevallen uw gegevens moeten blijven verwerken voor bepaalde legitieme doeleinden of om aan wet- en regelgeving te voldoen.  Indien deze rechten op u van toepassing zijn, kunt u ons verzoeken:</p>
 <ul>
   <li>Ik wil toegang krijgen tot of een kopie ontvangen van bepaalde persoonsgegevens die jullie over mij hebben.</li>
   <li>De verwerking van uw persoonsgegevens voor directe marketingdoeleinden te voorkomen (inclusief directe marketingverwerking gebaseerd op profilering).</li>
   <li>Gedateerde of onjuiste persoonsgegevens bij te werken.</li>
   <li>Bepaalde persoonsgegevens die wij over u hebben te verwijderen.</li>
   <li>Ik wil de manier waarop jullie specifieke persoonlijke informatie over mij verwerken en openbaar maken beperken.</li>
   <li>Uw persoonlijke informatie over te dragen aan een externe dienstverlener.</li>
   <li>Uw voorheen verleende toestemming voor het verwerken van uw persoonsgegevens in te trekken.</li>
 </ul>
 <p>Klik <a href="https://www.twitch.tv/p/legal/privacy-choices/">hier</a> voor meer informatie over het gebruik van deze rechten.  Indien van toepassing, kunt u een klacht indienen bij de toezichthoudende instantie voor gegevensbescherming van het land waarin u woonachtig bent. U kunt ook een rechtsmiddel aanwenden voor lokale rechtbanken indien u denkt dat uw rechten zijn geschonden.</p>
 <h4 id="account_closure_amp_deletion">Sluiting en verwijdering van uw account</h4>
 <p>Als u uw account wilt sluiten en uw profielgegevens wilt verwijderen van <a href="http://www.twitch.tv/">www.twitch.tv</a>, ga dan naar <a href="https://www.twitch.tv/user/delete_account">http://www.twitch.tv/user/delete_account.</a> Voor Twitch-diensten anders dan <a href="http://twitch.tv/">twitch.tv</a>, kunt u informatie gekoppeld aan uw account bijwerken of verwijderen, of een account sluiten, door naar het gedeelte "Mijn account" te gaan van de service of door een ondersteuningsverzoek in te dienen. Als u uw account sluit, bewaart Twitch mogelijk andere informatie over u inzake de activiteiten omschreven in deze Privacyverklaring, of voor zover toegestaan of vereist door toepasselijke wetgeving.</p>
 <h4 id="third_party_services_and_websites">Websites en diensten van derden</h4>
 <p>De Twitch-diensten verwijzen mogelijk door naar websites of diensten van derden. De handelswijzen met betrekking tot privacy van die derde partijen vallen niet onder deze Privacyverklaring. Wij raden u aan om het privacybeleid van deze websites en diensten van derden ter kennis te nemen om inzicht te krijgen in hun handelswijzen.</p>
 <p>Als u de Twitch-diensten koppelt aan een dienst van derden (zoals Facebook, Twitter of een andere applicatie van een derde partij) of anderzijds uw Twitch-account koppelt aan een externe dienst, verzoekt en autoriseert u ons om namens u gegevens te delen met, of toegang te verlenen tot, een dergelijke derde partij (zoals uw gebruikersnaam, het feit dat uw verbinding afkomstig is van de Twitch-diensten en andere relevante gebruiks- en diagnostische informatie). We sturen mogelijk ook informatie over de content die u kijkt of uw activiteiten op de Twitch-diensten naar dergelijke derde partijen. We maken bijvoorbeeld mogelijk informatie beschikbaar aan appontwikkelaars, gameontwikkelaars en gameuitgevers om aankopen en de overhandiging van digitale goederen, zoals games en in-game-items, mogelijk te maken.</p>
 <h4 id="extensions">Extensies</h4>
 <p>Het <a href="https://dev.twitch.tv/extensions">Twitch Extensie programma</a> geeft streamers de mogelijkheid om interactieve, aangepaste externe content en toepassingen in te bouwen op hun kanaalpagina\'s. U kunt meer informatie over de specifieke extensie(s) op een bepaald kanaal vinden door op de attributielinks of -iconen te klikken die Twitch beschikbaar maakt op de kanaalpagina; bijvoorbeeld op de Twitch-videospeler of onderaan het paneel van een extensie.</p>
 <p>Interactie door een kijker met een extensie of met het kanaal waarop de extensie geactiveerd is verschaft de ontwikkelaar van die extensie kijkerinformatie zoals hierboven omschreven onder "Automatisch verzamelde informatie". Twitch biedt binnen het Twitch Extensie programma derde-partijontwikkelaars van extensies geen toegang tot uw gebruikersnaam of -ID, tenzij u klikt op "Toegang verlenen" binnen de extensie of wanneer u een extensie installeert op uw kanaal. U bent zelf verantwoordelijk voor informatie die u op andere wijze aan de ontwikkelaar geeft, bijvoorbeeld via een online formulier op de extensie of door de website van de ontwikkelaar te bezoeken.</p>
 <p>Wij vereisen van extensieontwikkelaars dat zij gegevens over u uitsluitend verwerken voor de doeleinden die vermeld staan in onze <a href="https://www.twitch.tv/p/legal/developer-agreement/">ontwikkelaarsovereenkomst</a>. We raden u aan om naar de informatiepagina\'s van de extensie te gaan om het privacybeleid van de ontwikkelaar te beoordelen, dat mogelijk aanvullende informatie bevat over hun privacypraktijken.</p>
 <h4 id="advertisers_and_analytics_providers">Adverteerders en leveranciers van analytics</h4>
 <p>Twitch gebruikt mogelijk web-analyse-diensten van derde partijen voor de Twitch-diensten. Deze dienstverleners gebruiken een aantal trackingtechnologieën zoals cookies om te analyseren hoe gebruikers de Twitch-diensten gebruiken. De verzamelde informatie (hierboven omschreven onder "Automatisch verzamelde informatie") kan worden gedeeld met of rechtstreeks door deze dienstverleners worden verzameld en verwerkt om jouw gebruik van de Twitch-diensten te beoordelen.</p>
 <p>Twitch kan ook samenwerken met externe advertentienetwerken, adverteerders en aanbieders van advertentie-analyses om zowel op als buiten de Twitch-diensten advertenties op u te richten (en de prestaties daarvan te meten). We delen data als cookies en mobiele advertentie-ID\'s met deze derde partijen(of zij verzamelen mogelijk rechtstreeks) om advertentieactiviteiten te kunnen ondernemen (waaronder uw reactie op advertenties te begrijpen en om relevante advertenties weer te geven). Twitch werkt ook samen met derde partijen om u advertenties te tonen buiten de Twitch-diensten. Als we dat doen, delen we mogelijk informatie als uw e-mailadres of uw opnieuw instelbare apparaat-ID voor die advertentiepartner om dit te koppelen aan andere informatie die ze mogelijk over u hebben.</p>
 <p>Adverteerders op Twitch, of vertegenwoordigers of dienstverleners die namens hen werken ("Twitch-adverteerders"), gebruiken soms technologieën om advertenties die op onze diensten verschijnen rechtstreeks op uw apparaat weer te geven.  Ze ontvangen automatisch bepaalde data, zoals uw IP-adres, wanneer dit gebeurt. Ze kunnen ook cookies (of vergelijkbare technologieën) gebruiken om de effectiviteit van hun advertenties te meten en de inhoud van hun advertenties te personaliseren. Deze Privacyverklaring is niet van toepassing op de trackingtechnologieën en activiteiten van Twitch-adverteerders en we kunnen deze niet controleren. Raadpleeg daarvoor hun eigen privacybeleid. Ga naar onze pagina <a href="https://www.twitch.tv/p/legal/privacy-choices/">Privacy-opties</a> voor meer informatie over Twitch-adverteerders en vergelijkbare entiteiten die deze technologieën gebruiken, en om u af te melden van hun advertentiepraktijken.</p>
 <h4 id="do_not_track">Volg me niet</h4>
 <p>Do Not Track ("volg me niet", "DNT") is een privacyinstelling die gebruikers in bepaalde browsers kunnen instellen. DNT is een manier voor gebruikers om websites en diensten te laten weten dat zij niet willen dat bepaalde informatie over hun webpaginabezoeken gedurende langere tijd en bij meerdere websites of online diensten verzameld wordt. Wij zetten ons in om u zinvolle keuzes te bieden met betrekking tot de informatie die op onze website voor externe doeleinden verzameld wordt, en daarom verwijzen wij hierboven naar de opt-out-links van de Network Advertising Initiative, Your Online Choices en de Digital Advertising Alliance. Twitch erkent of reageert echter niet op DNT-signalen afkomstig van de browser.</p>
 <h4 id="data_security">Gegevensbeveiliging</h4>
 <p>Twitch heeft een aantal bestuurlijke, technische en fysieke maatregelen genomen om de integriteit en beveiliging van uw gegevens te waarborgen. Deze maatregelen kunnen variëren op basis van de gevoeligheid van uw informatie. Echter, geen enkele voorzorgsmaatregel of veiligheidssysteem is volledig waterdicht. We kunnen de beveiliging van informatie die u naar Twitch verstuurt niet garanderen, en u doet dit dan ook op eigen risico. We kunnen niet garanderen dat dergelijke informatie niet toegankelijke is, openbaar gemaakt, aangepast of vernietigd wordt als gevolg van een inbreuk op onze fysieke, technische of bestuurlijke veiligheidsmaatregelen.</p>
 <h4 id="retention_of_your_information">Bewaren van uw informatie</h4>
 <p>Twitch bewaart data over uw gebruik van Twitch zo lang als dit nodig is voor de relevante doeleinden zoals omschreven in deze Privacyverklaring, zoals mogelijk vereist (of toegestaan) door wetgeving, bijvoorbeeld voor belasting- en boekhoudkundige doeleinden, of anderzijds naar u gecommuniceerd. Als u ons vraagt om uw account te sluiten en uw profielinformatie te verwijderen, verwijderen we alle informatie die we wettelijk niet verplicht of toegestaan zijn om te bewaren.</p>
 <h4 id="children_rsquo_s_privacy">Privacy van kinderen</h4>
 <p>BENT U JONGER DAN 13 JAAR? MAAK DAN NOOIT EN OP GEEN ENKELE WIJZE GEBRUIK VAN DE TWITCH-DIENSTEN.</p>
 <p>De bescherming van de privacy van jonge kinderen is uitermate belangrijk. Daarom verzamelt of bewaart Twitch voor zover bekend is bij Twitch geen persoonsgegevens (zoals gedefinieerd door de Amerikaanse Children’s Online Privacy Protection Act) van personen jonger dan 13 jaar. Indien Twitch ontdekt dat persoonsgegevens van personen jonger dan 13 jaar zijn verzameld op of via de Twitch-diensten, zal Twitch gepaste maatregelen nemen om deze informatie te verwijderen.</p>
 <p>Indien u de ouder of wettelijke voogd bent van een kind jonger dan 13 jaar dat lid is geworden van de Twitch-diensten, neem dan contact op met Twitch via privacy@twitch.tv om het account van het kind en de persoonsgegevens te verwijderen.</p>
 <p>Voor inwoners van de EER, waar de verwerking van persoonsgegevens gebaseerd is op toestemming, zal Twitch zich niet willens en wetens bezighouden met dit soort verwerking bij gebruikers die te jong zijn om toestemming te geven, vastgesteld door toepasselijke wetgeving inzake gegevensbescherming. Als wij te weten komen dat we bij dergelijke gebruikers bezig zijn met die verwerking, zullen we dergelijke verwerking stoppen en zullen we redelijke maatregelen nemen om toepasselijke informatie onmiddellijk uit onze administratie te verwijderen.</p>
 <h4 id="merger_or_sale">Fusie of overname</h4>
 <p>In het geval dat Twitch, of sommige of alle activa gerelateerd aan de Twitch-diensten, wordt verworven door of fuseert met een derde partij of in connectie met een geplande verandering van eigenaar, behouden wij ons het recht voor om, onder al deze omstandigheden, de informatie die wij verzameld hebben van gebruikers over te dragen of toe te kennen als onderdeel van die fusie, overname, verkoop of verandering van eigenaar, waaronder gedurende het voorafgaande onderzoek.</p>
 <h4 id="international_data_transfers">Internationale doorgifte van gegevens</h4>
 <p>Informatie verzameld door Twitch wordt mogelijk opgeslagen en verwerkt in uw regio, in de Verenigde Staten (bijvoorbeeld in onze grote datacenters) of in andere landen waarin Twitch of haar gelieerden, dochterondernemingen, partners of dienstverleners gevestigd zijn of vestigingen hebben.  Indien wij informatie over u aan dergelijke entiteiten overhandigen, nemen wij de nodige maatregelen om ervoor te zorgen dat dergelijke bedrijven uw informatie voldoende beschermen in overeenstemming met deze Privacyverklaring en toepasselijke wetgeving.</p>
 <h4 id="changes_and_updates_to_this_privacy_notice">Wijzigingen en updates van deze Privacyverklaring</h4>
 <p>Twitch behoudt zich het recht voor om te allen tijde delen van deze Privacyverklaring te wijzigen, aan te passen, toe te voegen of verwijderen (bijvoorbeeld vanwege wijzigingen aan de Twitch-diensten of de wet). Controleer deze Privacyverklaring periodiek op die updates. Als u de Twitch-diensten na publicatie van wijzigingen blijft gebruiken, geldt dat als uw bindende acceptatie van dergelijke wijzigingen.</p>
 <p>Wij wijzigen ons beleid en onze handelswijzen niet zodanig dat ze persoonsgegevens die zijn verzameld in het verleden of onder een oudere versie van de Privacyverklaring minder effectief beschermen zonder toestemming van de getroffen personen.</p>
 <h4 id="twitch_contact_information">Twitch-contactinformatie</h4>
 <p>Neem voor vragen of opmerkingen over deze Privacyverklaring contact op met Twitch op 350 Bush Street, 2nd Floor, San Francisco, CA 94104, VS of door een e-mail te sturen naar privacy@twitch.tv. We reageren binnen 30 dagen na ontvangst op uw vraag. Als u inwoner van Californië bent, kunt u vragen om deze informatie per e-mail te ontvangen door een brief te sturen naar het bovenstaand adres met dit informatieverzoek en uw e-mailadres.</p>
 <p>Voor de doeleinden van de Algemene Verordening Gegevensbescherming is Twitch UK Limited door Twitch Interactive, Inc. aangewezen als vertegenwoordiger in de EU om namens dit bedrijf te handelen met betrekking tot verplichtingen onder Artikel 27 van de Algemene Verordening Gegevensbescherming. Neem contact op met Twitch UK voor vragen (waaronder vragen over uw rechten) of opmerkingen over deze Privacyverklaring via 1 New Oxford Street WC1A 1BA, UK of via een e-mail naar privacy@twitch.tv.</p>
 <h4 id="california_privacy_disclosures">Rechten omtrent het vrijgeven van persoonlijke informatie in Californië</h4>
 <p><a href="/p/nl-nl/legal/california-privacy-disclosure/"> Klik hier </a> om aanvullende informatie te lezen die vereist is onder de California Consumer Privacy Act en andere Californische wetten.</p>
 <h4 class="kr-only">Privacyverklaring Zuid-Korea</h4>
 <p class="kr-only">Onderstaande informatie is van toepassing op gebruikers in Zuid-Korea.</p>
 <p class="kr-only">Bewaren van persoonlijke informatie</p>
 <p class="kr-only">Uw persoonlijke gegevens worden bewaard en gebruikt voor de duur van uw zakelijke relatie met Twitch en zolang nodig is voor de wettelijke en regelgevende verplichtingen van Twitch, geschillenbeslechting, veiligheid en beveiliging van community\'s en sites en handhaving van contracten.</p>
 <p class="kr-only">Twitch verwijdert uw persoonlijke informatie in overeenstemming met het beleid voor gegevensbewaring van Twitch en de toepasselijke wetgeving. Nadat u uw account hebt gesloten, verwijdert Twitch uw persoonlijke informatie binnen redelijke tijd, op voorwaarde dat het vereist is of toegestaan om persoonlijke informatie te bewaren onder de toepasselijke wetgeving of zoals noodzakelijk voor de wettelijke en regelgevende verplichtingen van Twitch, geschillenbeslechting, veiligheid en beveiliging van community\'s en sites, en handhaving van contracten. Onder die omstandigheden wordt dergelijke informatie bewaard gedurende de periode die voor dergelijke doeleinden vereist is.</p>
 <p class="kr-only">Verwijderen van persoonlijke informatie </p>
 <p class="kr-only">Bij het verwijderen van persoonlijke informatie neemt Twitch standaard commercieel redelijke maatregelen om de persoonlijke informatie onherstelbaar of niet-reproduceerbaar te maken. De specifieke manier van verwijderen is afhankelijk van de informatie die wordt verwijderd en het type Twitch-diensten dat u hebt gebruikt. Elektronische documenten of bestanden die persoonlijke informatie bevatten, worden verwijderd met behulp van een technische methode die herstel of het ophalen van dergelijke informatie praktisch onmogelijk maakt of de gegevens niet langer persoonlijk identificeerbaar maakt. Niet-elektronische documenten of bestanden met persoonlijke informatie worden versnipperd, verbrand of beide.</p>
</div></div>']
?>
